language: java

jdk:
- oraclejdk8

script:
- ./gradlew check

before_cache:
- sudo rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

env:
  global:
  - ARTIFACTORY_SCM_USER=usr_artifactory_merc

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/