language: java
jdk:
- oraclejdk8

script: "./travis_script.sh"
branches:
  only:
    - master
cache:
  directories:
  - "~/.gradle/caches/"
  - "~/.gradle/wrapper/"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
env:
  global:
  - ARTIFACTORY_SCM_USER=usr_artifactory_merc
  - secure: "FulNz07ICIDPykeywcM2UhcPYV8yIwfxyKgmHBBCxG/BIElaRdmrbqBn2caYONb2vtaxXq6I3T+goCUgMNhUUGlLfhuFVbOrPjdjWXbkHmWBrxQ8+wV6OfRcWPx8FBPs8ZpJHa/zUTDZZA8wx7b52PRX9jRjPhoKlcHQZvvjo6qOieFpxiMla3/OyaxglMKg1uJU/H5xKANk4XN7UanJdOrTsKBc5g5eZGaHdMqwGL+W2+ZcDlru/NQyhLevDArDVQ2v4j02XKf/u3BePjGqeUotB8A8AniYZ+JuBGWLmTJrjsdxvHiyKa+ygTSv1vRVUyuRJy/is28fLMQSciR2OxX4R4UPo6o1V4xbFcjZu2sZWugKxmVn5ZiBSbBShp6tyyoe+8NKwlvlPEZcjCYCYqITtNzAeeb39UlF72ok8bocmUXPOIwHhJpaV3TKGkv4Z/YsyqPxwH11Mk841CrnW4jTvHfCYyCOPPmv7eEdNT/ko51jcmlCXkKR0gk/FvGQGWIPCr9nUzLKUzHiyKkpQNrtoMkPJ/R5TSc/2vajEejyKX42AaEIZ7X0Mcfh43PXDX+UkiZr0bg51ohE2aUpUAf8ZkYstYcLHC3FQbnuyaY9cDmMw1h+xwpKTN6/Vm50+owbMvLZA6W3HROf9wqQQmdYBZBWaKvDSRLZD6VB3sk=" #ARTIFACTORY_SCM_PASSWORD
  - secure: "ltpKaoxL/bsug/AnrRTuSmEhTFUP/oSa9jfWeR3umcbbbeMx5JBAtN5+5VoQX+52b+TRksw+tZYPB0ig9wW4It9gd2FL4wwLtmbgbWsmBvrRL1KSSerL1vQ7i0/4cJm1knzE5IAjbtShWXWO8ebxpFThQXUJ3+o0hqPa/nezAm4T6dTEpmN+GbF3RHuOTB7opkoOxGfOcZ8baNLTZiM1K3EwnsQn8n+U/Efw3SoWtyJHmVItCKwF5ucMHt0RwHw3e1+8PXJREOsbRutX+gTVoN29E9BcJ4xAiublPn3kA9YVC3gnbgR54xCRm1JPdh9JUcgzzEsOjgnAicUV9nqdibAROApCWDRQ6lLp5Dir2biJIPtFj0S5b/uGxcVEh2KvLNIT9cdj5UaeE1LsA1pUiDBv6Tu3OzC96IzdCsFp9O7goFRZFEH0ErYIvrZfWGuZZTQwMhCRySw/05AMYFB0FL8hspidfc5zIqOseqHJyXZVFjMcnlUdKY0AXXccaN5dzl3rGm1n3UwZ2HPhff494U4IfH+BwSoQ4bfjuFqMKUJL8D+NE+YaCSvtuFbDN+och1xEsn6H92L1RoMGbZI5eUIFEdl/Vz+dbiC8KTAxtA+aH16r6VHKe0wEthLQygZz/oSew98ejYXqyy377n5UB7r2XoPRetQPJ6vKCzZ+lFw=" # SONAR_TOKEN

deploy:
  provider: script
  script: "./travis_deploy.sh"
  skip_cleanup: true
  on:
    branch: "master"
